# Generated by Django 4.2.5 on 2023-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='title',
            new_name='en_title',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='body',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='en_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='fr_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='fr_title',
            field=models.CharField(default='defaulft', max_length=255),
            preserve_default=False,
        ),
    ]
